### PR TITLE
add typescript typings

### PR DESCRIPTION
**Pull request by jomel**

### CODE REVIEW

**Comment by jomel** [comment]
@peterhaldbaek

**Comment by peterhaldbaek** [comment]
Thanks for the contribution! I am a little undecided on whether I want to merge this or not as I don't like having duplicated documentation and I don't use Typescript myself (yet). Any advantages I am missing with this PR?

**Comment by jomel** [comment]
The biggest advantage is that people usi g your package in typescript get inline code completion, attribute suggestions and type checking etc.
Otherwise we need to manually add an override typing file for this library (what I do right now) bevmcause we get undefined type errors from the compiler - just wanted to save someone else the same work ;)

**Comment by peterhaldbaek** [comment]
Thanks for clarifying. I will merge and then do a new release.

**Pull request merged**
